### ISSUE TITLE
reject errors?

### ISSUE THREAD

**Issue by karussell** [graphhopper/directions-api-js-client#30]
At this line there is a resolve https://github.com/graphhopper/directions-api-js-client/blob/master/src/GraphHopperOptimization.js#L124

Is this correct or should it be reject?

**Comment by boldtrn** [comment]
Sorry I must have missed this issue :). I introduced this resolve in [this commit](https://github.com/graphhopper/directions-api-js-client/commit/c5aa870b399e49af206f19f1021a04b995181c00#diff-622c155103d90dcf55da08e420f14097L120). I might have misinterpreted this case, because for other APIs we do 
```
if (err || !res.ok) {
   reject(ghUtil.extractError(res, url));
}
```
The other cases are assumed to be correct cases. If this case would be indeed an error situation, then we should reject and not resolve. Should I create a PR for this?

**Comment by karussell** [comment]
This is a critical part of the code. 

We should poll until either "finished" is set, an http error happend or the JSON is an error message (an http error should be associated as well). 

Or maybe it is safer to poll only if status is `waiting` or `processing`? WDYT @oblonski ?

**Comment by karussell** [comment]
I think this is fixed.
